#!/bin/bash
git add .
git commit -m $1
git push https://Abel-D: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@github.com/Abel-D/alx-system_engineering-devops.git 
